services:
    mailpit:
        container_name: ${COMPOSE_PROJECT_NAME}-mailpit
        image: axllent/mailpit
        volumes:
            - ${DATA_DIR}/mailpit:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1